### ISSUE TITLE
FastAPI: AttributeError: type object 'HealthSummary' has no attribute '__pydantic_model__'

### ISSUE THREAD

**Issue by uwohlfeil** [SolarEdgeTech/pyctuator#90]
The current version of FastAPI (0.92.0) does not seem to work with the current Pyctuator (1.0.1).

I found a discussion about this in FastApi's GIT:
https://github.com/tiangolo/fastapi/issues/3636

The cause of the problem seems to be a change in the Change https://github.com/tiangolo/fastapi/pull/3576 .

The built-in dataclasses do not seem to be fully compatible with FastAPI when using enums.

As a test, I changed the dataclasses in health/health_provider.py to:
```python
from pydantic.dataclasses import dataclass
```
And it works again.

Update:
The error does not occur in FastAPI version 0.88.0.

**Comment by michaelyaakoby** [comment]
Thanks, will try to get to this soon.

**Comment by michaelyaakoby** [comment]
This is the same issue as #87.
Fixed in https://github.com/SolarEdgeTech/pyctuator/pull/91

**Comment by michaelyaakoby** [comment]
Version 1.0.2

**Comment by uwohlfeil** [comment]
@michaelyaakoby 
Thank you very much for your work. 
Just test it and it works.
